name: Tests

on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest
    working-directory: server

    steps: 
    - uses: actions/checkout@v2
    
    - run: cd server && npm install && npm run tes 
    
